version: "3.8"

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "32M"
    restart: unless-stopped
