version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:3000" # Todo el tráfico al puerto 3000 pasa por NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-server
    networks:
      - node-network

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
